---
- name: Install Docker and Docker Compose
  hosts: your_target_servers
  become: yes  # Run tasks with elevated privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install Docker Compose
      command: "pip3 install docker-compose"

    - name: Add the user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      notify: Restart Docker

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
